leet_88: leet_88.c munit.c
	gcc -g leet_88.c munit.c -o leet_88.out

leet_27: leet_27.c munit.c
	gcc -g leet_27.c munit.c -o leet_27.out

leet_26: leet_26.c munit.c
	gcc -g leet_26.c munit.c -o leet_26.out

clean:
	rm leet_26 leet_27 leet_88
